export const CARD_STYLES = 'w-full max-w-md rounded-2xl bg-card p-8 ring-1 ring-foreground/10';
export const TITLE_STYLES = 'font-heading text-2xl font-semibold';
export const SUBTITLE_STYLES = 'mt-1 text-sm text-muted-foreground';
export const formStyles = 'mt-6 flex flex-col gap-4';
export const inputStyles = 'w-full';
export const LABEL_ROW_STYLES = 'flex items-center justify-between';
export const forgotPasswordStyles = 'text-xs text-muted-foreground hover:text-foreground';
export const buttonStyles = 'w-full';
export const linkStyles = 'font-medium text-primary underline-offset-4 hover:underline';
