"""noop placeholder (empty auto-generated revision, no schema changes)

Revision ID: 0843c71159ef
Revises: cbb4b92ca9fe
Create Date: 2026-07-22 18:43:52.183101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0843c71159ef'
down_revision: Union[str, Sequence[str], None] = 'cbb4b92ca9fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
