"""add practice product flow

Revision ID: cbb4b92ca9fe
Revises: e78523a6497e
Create Date: 2026-07-22 18:08:33.181941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbb4b92ca9fe'
down_revision: Union[str, Sequence[str], None] = 'e78523a6497e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_session_questions',
    sa.Column('id', sa.Integer(), sa.Identity(), nullable=False),
    sa.Column('practice_session_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='assigned', nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['practice_session_id'], ['practice_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_session_questions_practice_session_id'), 'practice_session_questions', ['practice_session_id'], unique=False)
    op.create_index(op.f('ix_practice_session_questions_question_id'), 'practice_session_questions', ['question_id'], unique=False)
    op.add_column('practice_sessions', sa.Column('mode', sa.String(length=50), server_default='adaptive', nullable=False))
    op.add_column('practice_sessions', sa.Column('question_count', sa.Integer(), server_default='25', nullable=False))
    op.add_column('questions', sa.Column('section', sa.String(length=50), server_default='math', nullable=False))
    op.create_index(op.f('ix_questions_section'), 'questions', ['section'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_section'), table_name='questions')
    op.drop_column('questions', 'section')
    op.drop_column('practice_sessions', 'question_count')
    op.drop_column('practice_sessions', 'mode')
    op.drop_index(op.f('ix_practice_session_questions_question_id'), table_name='practice_session_questions')
    op.drop_index(op.f('ix_practice_session_questions_practice_session_id'), table_name='practice_session_questions')
    op.drop_table('practice_session_questions')
    # ### end Alembic commands ###
