export const GREETING_PREFIX = 'Welcome back, ';
export const GREETING_EXCLAMATION = '!';
export const SECTIONS_TITLE = 'Practice Sections';
export const ERROR_MESSAGE = 'Failed to load dashboard data. Please try again.';
export const RETRY_BUTTON = 'Retry';
export const SESSIONS_LABEL = 'Sessions Completed';
export const QUESTIONS_LABEL = 'Questions Answered';
export const ACCURACY_LABEL = 'Accuracy';
export const PERCENT_SUFFIX = '%';
